Job: ef_higher_ord
Updated to force higher order networks to have approximately the same
number of parameters as swish network. Decreased channel multiplier
for triple activation function networks. Fixing bug:

File "/content/pytorch-image-models/activation_functions.py", line 133, in activate
    x = x.reshape(batch_size, int(num_channels * p / k), k, height, width)
RuntimeError: shape '[96, 5, 2, 1, 1]' is invalid for input of size 1056